### ISSUE TITLE
how to use codeToHtml + transformer (meta) ?

### ISSUE THREAD

**Issue by felixsanz** [shikijs/shiki#703]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Using this pretty simple example:

```js
import { codeToHtml } from 'shiki'
import { transformerMetaHighlight } from '@shikijs/transformers'

const code = 'const a = 1'
const html = await codeToHtml(code, {
  lang: 'javascript',
  theme: 'vitesse-dark',
  transformers: [
    transformerMetaHighlight(),
  ],
})

console.log(html)
```

How do you pass the meta highlight configuration? eg. `{1,3-4}` ?

### Reproduction

can't reproduce something doesn't exist

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by fuma-nama** [comment]
> How do you pass the meta highlight configuration? eg. {1,3-4} ?

This is unsupported. Meta string is actually related to markdown/MDX syntax, for example:

````md
```ts this is meta string!
console.log("Hello")
```
````

The function `codeToHtml` doesn't support markdown or MDX directly, you have to use it with integrations like `rehype-shiki` or markdown-it integration.

**Comment by felixsanz** [comment]
> > How do you pass the meta highlight configuration? eg. {1,3-4} ?
> 
> This is unsupported. Meta string is actually related to markdown/MDX syntax, for example:
> 
> ```
> ```ts this is meta string!
> console.log("Hello")
> ```
> ```
> 
> The function `codeToHtml` doesn't support markdown or MDX directly, you have to use it with integrations like `rehype-shiki` or markdown-it integration.

it is possible to integrate it like this?

```javascript
import { codeToHtml } from 'shiki'
import { transformerMetaHighlight } from '@shikijs/transformers'

const code = 'const a = 1'
const html = await codeToHtml(code, {
  lang: 'javascript',
  theme: 'vitesse-dark',
  transformers: [
    transformerMetaHighlight({ options }, '1,3-4'), // <-----
  ],
})

console.log(html)
```

**Comment by fuma-nama** [comment]
If you mean to hardcode the meta string, yes, you can pass the meta string with `meta` option:

https://github.com/shikijs/shiki/blob/ff1d2f881c7381808de12666a80480dab1897a1e/packages/core/src/types/options.ts#L162

Of course I'll recommend notation transformers if possible, it's more straightforward than meta transformers.

**Comment by hddhyq** [comment]
@felixsanz 
https://github.com/shikijs/shiki/blob/ff1d2f881c7381808de12666a80480dab1897a1e/packages/transformers/src/transformers/transformer-meta-highlight.ts#L34-L54

It seems that it should be used like this.
```
  highlighter.codeToHtml(code, {
    lang: 'javascript',
    theme: 'github-dark',
    transformers: [transformerMetaHighlight()],
    meta: {
      __raw: '{1,3-4}',
    },
  });
```

**Comment by felixsanz** [comment]
thank you both! that's so useful
