### ISSUE TITLE
Twoslash: `meta` is passed to the popup types codeblock

### ISSUE THREAD

**Issue by fuma-nama** [shikijs/shiki#747]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

See https://github.com/shikijs/shiki/blob/69b32a33e097231eaf4a0968e78d97b70c0e3f90/packages/twoslash/src/renderer-rich.ts#L242

The meta options from Twoslash transformer is passed to another `this.codeToHast` to render codeblocks in popups.
However, the meta isn't supposed to be inherited on child codeblocks.

An example is that if we have a `title` meta like `{ title: "Test", __raw: "something else" }`, this will cause the code blocks in popups also inherit the same title.

![image](https://github.com/user-attachments/assets/34584204-3b91-462a-9c56-f63be8e57035)

### Reproduction

https://codesandbox.io/p/devbox/amazing-fast-gkzsks

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests
